package gr.dit.hua.it22023.it22003.GUI;

import javax.swing.*;
import java.awt.*;

public class GUI extends JFrame
{
    
    private JPanel Main_Panel;
    private JTextField ageTextField;
    private JButton confirmButton;
    private JLabel ageLabel;
    
    public GUI(String title) throws HeadlessException
    {
        super(title);
        initComponents();
        this.setLayout(null);
        this.setPreferredSize(new Dimension(400 , 100));
        this.setContentPane(Main_Panel);
        this.pack();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
    
    
    private void initComponents()
    {
    }
    
    public static void CreateGUI()
    {
        GUI GUI = new GUI("Travel Advisor");
        
        
    }
    
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        Main_Panel = new JPanel();
        Main_Panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2 , 4 , new Insets(0 , 0 , 0 , 0) , - 1 , - 1));
        ageTextField = new JTextField();
        Main_Panel.add(ageTextField , new com.intellij.uiDesigner.core.GridConstraints(1 , 1 , 1 , 1 , com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST , com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL ,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW ,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW , null , new Dimension(50 , - 1) , null , 0 , false));
        confirmButton = new JButton();
        confirmButton.setText("Button");
        Main_Panel.add(confirmButton , new com.intellij.uiDesigner.core.GridConstraints(1 , 3 , 1 , 1 , com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER , com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL ,
                                                                                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW , com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED , null , null , null , 0 , false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        Main_Panel.add(spacer1 , new com.intellij.uiDesigner.core.GridConstraints(1 , 2 , 1 , 1 , com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER , com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL , com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW , 1 , null , null , null , 0 , false));
        ageLabel = new JLabel();
        ageLabel.setText("Age:");
        Main_Panel.add(ageLabel , new com.intellij.uiDesigner.core.GridConstraints(0 , 1 , 1 , 1 , com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST , com.intellij.uiDesigner.core.GridConstraints.FILL_NONE , com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED , com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED , null , null , null , 0 , false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        Main_Panel.add(spacer2 , new com.intellij.uiDesigner.core.GridConstraints(1 , 0 , 1 , 1 , com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER , com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL , com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW , 1 , null , null , null , 0 , false));
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return Main_Panel;
    }
}
