package gr.dit.hua.it22023.it22003.GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class GUI extends JFrame
{
    
    private JPanel Main_Panel1;
    private JTextField ageTextField;
    private JButton confirmButton;
    private JLabel ageLabel;
    
    public GUI(String title) throws HeadlessException {
        super(title);
        initComponents();
        this.setLayout(null);
        this.setPreferredSize(new Dimension(400 , 100));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setContentPane(Main_Panel1);
        this.pack();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
    
    
    private void initComponents() {
        this.ageLabel.setText("Please enter your age");
    }
    
    public static void CreateGUI()
    {
        GUI GUI = new GUI("Travel Advisor");
        
        
    }
    
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        Main_Panel1 = new JPanel();
        Main_Panel1.setLayout(new GridLayoutManager(2 , 4 , new Insets(0 , 0 , 0 , 0) , - 1 , - 1));
        ageTextField = new JTextField();
        Main_Panel1.add(ageTextField , new GridConstraints(1 , 1 , 1 , 1 , GridConstraints.ANCHOR_WEST , GridConstraints.FILL_HORIZONTAL ,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                           GridConstraints.SIZEPOLICY_CAN_GROW , GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                                                 GridConstraints.SIZEPOLICY_CAN_GROW , null , new Dimension(50 , - 1) , null , 0 , false));
        confirmButton = new JButton();
        confirmButton.setText("Button");
        Main_Panel1.add(confirmButton , new GridConstraints(1 , 3 , 1 , 1 , GridConstraints.ANCHOR_CENTER , GridConstraints.FILL_HORIZONTAL ,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                            GridConstraints.SIZEPOLICY_CAN_GROW , GridConstraints.SIZEPOLICY_FIXED , null , null , null , 0 , false));
        final Spacer spacer1 = new Spacer();
        Main_Panel1.add(spacer1 , new GridConstraints(1 , 2 , 1 , 1 , GridConstraints.ANCHOR_CENTER , GridConstraints.FILL_HORIZONTAL , GridConstraints.SIZEPOLICY_WANT_GROW , 1 , null , null , null , 0 , false));
        ageLabel = new JLabel();
        ageLabel.setText("Age");
        Main_Panel1.add(ageLabel , new GridConstraints(0 , 1 , 1 , 1 , GridConstraints.ANCHOR_WEST , GridConstraints.FILL_NONE , GridConstraints.SIZEPOLICY_FIXED , GridConstraints.SIZEPOLICY_FIXED , null , null , null , 0 , false));
        final Spacer spacer2 = new Spacer();
        Main_Panel1.add(spacer2 , new GridConstraints(1 , 0 , 1 , 1 , GridConstraints.ANCHOR_CENTER , GridConstraints.FILL_HORIZONTAL , GridConstraints.SIZEPOLICY_WANT_GROW , 1 , null , null , null , 0 , false));
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return Main_Panel1;
    }
}
