package gr.dit.hua.it22023.it22003.GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MainGUI extends JFrame
{
    private JPanel MainPanel;
    
    public MainGUI(String title) throws HeadlessException
    {
        super(title);
        this.setLayout(null);
        this.setPreferredSize(new Dimension(500 , 500));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setContentPane(MainPanel);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        AgeSelectionWindow ageSelectionWindow = new AgeSelectionWindow("peos" , this);
    }
    
    public static void CreateGUI()
    {
        MainGUI GUI = new MainGUI("Travel Advisor");
        
        
    }
    
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1 , 1 , new Insets(0 , 0 , 0 , 0) , - 1 , - 1));
        final JLabel label1 = new JLabel();
        label1.setText("TEST");
        MainPanel.add(label1 , new GridConstraints(0 , 0 , 1 , 1 , GridConstraints.ANCHOR_WEST , GridConstraints.FILL_NONE , GridConstraints.SIZEPOLICY_FIXED , GridConstraints.SIZEPOLICY_FIXED , null , null , null , 0 , false));
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return MainPanel;
    }
    
}
